{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "email-oauth2-proxy.namespace" . }}
data:
  {{ .Values.configMap.key }}: |
{{ .Values.configMap.data | nindent 4 }}
{{- end }}