apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-cache-store
  namespace: {{ include "email-oauth2-proxy.namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-config-store
  namespace: {{ include "email-oauth2-proxy.namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
