{{- if and .Values.tls.cert .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: certificate
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
