apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "email-oauth2-proxy.serviceAccountName" .}}
  namespace: {{ include "email-oauth2-proxy.namespace" . }}
  labels:
  {{- include "email-oauth2-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
