apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-oauth2-proxy.fullname" . }}
  namespace: {{ include "email-oauth2-proxy.namespace" . }}
  labels:
    {{- include "email-oauth2-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: imaps
      port: {{ .Values.service.ports.imaps.port }}
      targetPort: {{ .Values.service.ports.imaps.targetPort }}
      protocol: {{ .Values.service.ports.imaps.protocol }}
    - name: pop3
      port: {{ .Values.service.ports.pop3.port }}
      targetPort: {{ .Values.service.ports.pop3.targetPort }}
      protocol: {{ .Values.service.ports.pop3.protocol }}
    - name: pop3s
      port: {{ .Values.service.ports.pop3s.port }}
      targetPort: {{ .Values.service.ports.pop3s.targetPort }}
      protocol: {{ .Values.service.ports.pop3s.protocol }}
    - name: smtp
      port: {{ .Values.service.ports.smtp.port }}
      targetPort: {{ .Values.service.ports.smtp.targetPort }}
      protocol: {{ .Values.service.ports.smtp.protocol }}
  selector:
    {{- include "email-oauth2-proxy.selectorLabels" . | nindent 4 }}
