# Default values for email-oauth2-proxy
replicaCount: 1

image:
  repository: docker.io/pjaudiomv/email-oauth2-proxy
  tag: 1.0.0
  pullPolicy: Always
  ## pullSecrets:
  ##   - name: myRegistryKeySecretName
  # -- pull secrets

setupPod:
  enabled: false

# Optionally mount a custom emailproxy.config from a ConfigMap
configMap:
  enabled: false
  name: emailproxy-config
  key: emailproxy.config
  data: |
    [smtp] etc

# useful if wanting to set local_key_path and local_certificate_path
tls:
  cert:
  key:

service:
  type: ClusterIP
  ports:
    imaps:
      port: 2993
      targetPort: 2993
      protocol: TCP
    pop3:
      port: 110
      targetPort: 110
      protocol: TCP
    pop3s:
      port: 2995
      targetPort: 2995
      protocol: TCP
    smtp:
      port: 1587
      targetPort: 1587
      protocol: TCP

# Additional command line arguments
args: []

# can be useful for AWS IRSA for cache
serviceAccount:
  annotations: {}

# K/V ENV Vars
config: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
