name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
      - '!v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: short_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: |
            pjaudiomv/email-oauth2-proxy
          tags: |
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title="Email OAuth 2.0 Proxy"
            org.opencontainers.image.description="An IMAP/POP/SMTP proxy that transparently adds OAuth 2.0 authentication for email clients that don't support this method. "
            org.opencontainers.image.version="${{ github.ref_type == 'tag' && github.ref_name || steps.short_sha.outputs.SHA_SHORT }}"
            org.opencontainers.image.licenses="Apache License 2.0"
            org.opencontainers.image.documentation="https://github.com/pjaudiomv/email-oauth2-proxy/README.md"
          annotations: |
            org.opencontainers.image.title="Email OAuth 2.0 Proxy"
            org.opencontainers.image.description="An IMAP/POP/SMTP proxy that transparently adds OAuth 2.0 authentication for email clients that don't support this method. "
            org.opencontainers.image.version="${{ github.ref_type == 'tag' && github.ref_name || steps.short_sha.outputs.SHA_SHORT }}"
            org.opencontainers.image.licenses="Apache License 2.0"
            org.opencontainers.image.documentation="https://github.com/pjaudiomv/email-oauth2-proxy/README.md"
            org.opencontainers.image.source=https://github.com/pjaudiomv/email-oauth2-proxy
            org.opencontainers.image.revision="${ steps.short_sha.outputs.SHA_SHORT }}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64/v8
